# Production-specific overrides
version: '3.8'

services:
  backend:
    build:
      target: production
    restart: always
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  frontend:
    build:
      target: production
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  redis:
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  mongodb:
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M