version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6380"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: namenamename
    volumes:
      - mongodb_data:/data/db

volumes:
  redis_data:
  mongodb_data: